# Generated by Django 5.2.17 on 2026-08-15 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estudiante', models.CharField(max_length=100)),
                ('curso', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('presente', models.BooleanField(default=True)),
            ],
        ),
    ]
